/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    id: 1,
    title: "Yeh hasi wadiyan | Roja | Madubal, Arwind Swami |Chitra,S.P.Balasubhramanyam, A. R. Rahman",
    channel: "AR WORLD",
    date: "Aug 15, 1992",
    embedLink: "https://youtu.be/QPHRCURVA80",
    category:"Hindi",
  },
  {
    id: 2,
    title: "Ishq Bina | Taal | Aishwarya Rai, Akshaye | Anuradha Sriram, Sujatha, Sonu Nigam, A. R. Rahman",
    channel: "AR WORLD",
    date: "Aug 13, 1999",
    embedLink: "https://youtu.be/zSCevtX7ud0",
    category:"Hindi",
  },
  {
    id: 3,
    title: "Dil Se Re | Dil Se | Manisha Koirala, Shahrukh Khan | Anuradha Sriram,Febi, A. R. Rahman",
    channel: "AR WORLD",
    date: "Aug 21, 1998",
    embedLink: "https://youtu.be/8ToEwbzM-0c",
    category:"Hindi",
  },
  {
    id: 3,
    title: "Yun Hi Chala |Swades| Gayatri Joshi, Shahrukh Khan | Udit Narayan, Hariharan, Kailash Kher A. R. Rahman",
    channel: "AR WORLD",
    date: "Dec 17, 2004",
    embedLink: "https://youtu.be/eEeX2QMlSlo",
    category:"Hindi",
  },
  {
    id: 4,
    title: "Radha Kaise Na Jale |Lagan| Grecy Singh, Amir Khan | Udit Narayan,Asha Bholse, A. R. Rahman",
    channel: "AR WORLD",
    date: "June 15, 2001",
    embedLink: "https://youtu.be/qNnvL0ztJhA",
    category:"Hindi",
  },
  {
    id: 5,
    title: "Chanda Re Chanda |Sapney| Kajol, Prabhudeva |Hariharn,Sdhna Sargam A. R. Rahman",
    channel: "AR WORLD",
    date: "Jan 14, 1997",
    embedLink: "https://youtu.be/Sg1aIfA1bIM",
    category:"Hindi",
  },
  {
    id: 6,
    title: "Mersal - Neethanae Tamil Video | Vijay, Samantha | A.R. Rahman",
    channel: "AR WORLD",
    date: "Jan 14, 2018",
    embedLink: "https://youtu.be/fWajtP80g54",
    category:"Tamil",
  },
  {
    id: 7,
    title: "Vinnaithaandi Varuvaayaa - Hosanna Video | Rahman | STR, Trisha",
    channel: "AR WORLD",
    date: "Aug 12, 2012",
    embedLink: "https://youtu.be/YFYiTS46x-8",
    category:"Tamil",
  },
  {
    id: 8,
    title: "Sillunu Oru Kadhal | Munbe Vaa Song | Suriya | Bhumika | Jyothika | AR Rahman",
    channel: "AR WORLD",
    date: "Dec 12, 2012",
    embedLink: "https://youtu.be/juHpoMK3AuQ",
    category:"Tamil",
  },
  {
    id: 9,
    title: "Naan Un | 24 | Suriya | Samntha | Arijit Singh, AR Rahman",
    channel: "AR WORLD",
    date: "Dec 12, 2012",
    embedLink: "https://youtu.be/jRDCWQP7rjI",
    category:"Tamil",
  },
  {
    id: 10,
    title: "Enna sona Concert iifa Rocks |  AR Rahman",
    channel: "AR WORLD",
    date: "Dec 12, 2018",
    embedLink: "https://youtu.be/CgIVv6Und-0",
    category:"Concert",
  },
  {
    id: 11,
    title: "Tere Bina | Guru-Concert Bangladesh |  AR Rahman",
    channel: "AR WORLD",
    date: "Dec 12, 2018",
    embedLink: "https://youtu.be/CgIVv6Und-0",
    category:"Concert",
  },
  
  {
    id: 12,
    title: "Lukka Chuppi | Dubai Expo | Lata Mangeshkar, AR Rahman",
    channel: "AR WORLD",
    date: "Dec 12, 2022",
    embedLink: "https://youtu.be/iZyQ7s3qpBM",
    category:"Concert",
  },
  {
    id: 13,
    title: "Dil se  | Chennai Concert| Lata Mangeshkar, AR Rahman",
    channel: "AR WORLD",
    date: "Dec 30, 2020",
    embedLink: "https://youtu.be/p0YJLN3nQoM",
    category:"Concert",
  },
  {
    id: 14,
    title: "Bobamy Theme | Berklee college of Music|  AR Rahman",
    channel: "AR WORLD",
    date: "Dec 30, 2020",
    embedLink: "https://youtu.be/fgjjJOZkXbQ",
    category:"Berklee",
  },
  {
    id: 15,
    title: "Jiya Jale | Berklee college of Music|  AR Rahman",
    channel: "AR WORLD",
    date: "Dec 30, 2014",
    embedLink: "https://youtu.be/fgjjJOZkXbQ",
    category:"Berklee",
  },
  
  {
    id: 16,
    title: "Chaiya chaiya  | Berklee college of Music|  AR Rahman",
    channel: "AR WORLD",
    date: "Dec 30, 2014",
    embedLink: "https://youtu.be/HZbprgd2Rus",
    category:"Berklee",
  },
  
  {
    id: 17,
    title: "Jai Ho A Film On -AR Rahman",
    channel: "AR WORLD",
    date: "Aug 04, 2020",
    embedLink: "https://youtu.be/GQrPtMFQ050",
    category:"Documentry",
  },
  
  {
    id: 17,
    title: "A. R. RAHMAN || MEGA ICON || NATIONAL GEOGRAPHY || HINDI BIOGRAPHY",
    channel: "AR WORLD",
    date: "Aug 04, 2020",
    embedLink: "https://youtu.be/YppvZNRvJIc",
    category:"Documentry",
  },
];
